In [ ]:
pip install ucimlrepo


In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [ ]:
y["class"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
y["class"].duplicated().sum()


np.int64(147)

In [ ]:
#importin libaries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,recall_score,precision_score

In [ ]:
#train,test,split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#logistic regression
lr_model=LogisticRegression()
lr_model.fit(X_train,y_train)


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
y_test[0:5]

,class
73,Iris-versicolor
18,Iris-setosa
118,Iris-virginica
78,Iris-versicolor
76,Iris-versicolor


In [ ]:
#decision tree evaluation:
Accuracy=accuracy_score(y_test,lr_pred)
print(f"accuracy:{Accuracy}")
Recall_lr=recall_score(y_test,lr_pred,average="weighted")
print(f"Recall:{Recall_lr}")
Precision_lr=precision_score(y_test,lr_pred,average="weighted")
print(f"Precision:{Precision_lr}")
cm=confusion_matrix(y_test,lr_pred)
print(f"Confusion Matrix:\n{cm}")
cr=classification_report(y_test,lr_pred)
print(f"Classification Report:\n{cr}")

accuracy:1.0
Recall:1.0
Precision:1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



You're seeing the results of evaluating the logistic regression model on the test data. Here's what each part of the outcome means:

Accuracy: 1.0: This means the model correctly predicted 100% of the flower species in the test set. All 30 instances in your test set were classified correctly.

Recall: 1.0 (weighted average): This indicates that for each class ('Iris-setosa', 'Iris-versicolor', 'Iris-virginica'), the model correctly identified all instances of that class. There were no false negatives.

Precision: 1.0 (weighted average): This means that when the model predicted a certain class, it was always correct. There were no false positives.

Confusion Matrix:

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
This matrix shows the number of correct and incorrect predictions per class. Each row represents the actual class, and each column represents the predicted class. Here:

10 'Iris-setosa' samples were correctly predicted as 'Iris-setosa'.
9 'Iris-versicolor' samples were correctly predicted as 'Iris-versicolor'.
11 'Iris-virginica' samples were correctly predicted as 'Iris-virginica'. The zeros elsewhere confirm there were no misclassifications.
Classification Report: This provides a detailed breakdown of precision, recall, and f1-score for each class:

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30
All scores are 1.00, reinforcing that the model achieved perfect classification on this particular test set. The support column shows the number of true instances for each class in the test set. This is an exceptional result, indicating the logistic regression model performed perfectly on your Iris dataset test set.

In [ ]:
#decision tree
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
dt_model_pred=dt_model.predict(X_test)
dt_model_pred[0:5]

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [ ]:
#random forest classifier
rf_model=RandomForestClassifier()
rf_model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [ ]:
rf_model_pred=rf_model.predict(X_test)
rf_model_pred[0:5]

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [ ]:
import pickle as pk
import joblib

In [ ]:
joblib.dump(lr_model,"lr_model.joblib")
pk.dump(lr_model,open("lr_model.pkl","wb"))
